name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Récupération du code
      - uses: actions/checkout@v3

      # 2) Installation du JDK 17 + cache Maven
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # 3) Build et tests unitaires
      - name: Build & tests
        run: mvn -B verify

      # 4) Analyse SonarCloud
      - name: SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B sonar:sonar \
            -Dsonar.projectKey=sofian_demo1 \
            -Dsonar.organization=bobyxoxo \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
